DEFAULT_TASK_PROMPT = "Text: {input}"

LABELS = {
    "Background": "Background",
    "Motivation": "Objective",
    "Method": "Method",
    "Result": "Result",
    "Conclusion": "Conclusion",
}

CORESC_DEFINTION = {
    "Background": "The label to use for any background information (about pre-existing, already "
    "known entities). For example, use this label if the sentence contains background related "
    "to the current work. Please use this category sparingly and after you have made sure that a sentence "
    "does not fall into any of the other categories.",
    "Conclusion": "Refer to statements inferred from observations and results, which support or reject a "
    "research hypothesis or summarise the findings of an investigation. A conclusion should answer the "
    "question of whether the target or targets of the investigation have been met, whether a hypothesis "
    "has been confirmed or refuted and what new contribution to knowledge has been achieved through "
    "the investigation. Conclusions are not direct interpretations of observations in the way that results "
    "are but rather present the broader picture and the overall impact of the investigation.",
    "Method": "The means by which the authors seek to achieve a goal of the "
    "investigation. A research method is a way to solve a scientific task “based upon or regulated by "
    "science, as opposed to mere traditional rules or empirical dexterity” [OED]. "
    "Sentences which provide general, not direct or specific, information about experiments of an "
    "investigation should also be marked as with this label.",
    "Motivation": "A sentence that indicates why the investigation is important should be annotated with this label. "
    "Motivation for an investigation is the stimulus for achieving the goal of the investigation, the reason "
    "to carry out the investigation. The motivation is not always explicitly stated in the paper but when "
    "present it is usually mentioned in the Abstract and/or the Introduction sections. It is normally "
    "phrased as a problem whose resolution is of vital importance for the current investigation.",
    "Result": "Statements about the outputs of an investigation in the form of facts, or factual "
    "statements, supported by the observations and other results. Results of the investigation are "
    "obtained through the interpretation or comparison of observations.",
}

CORESC_EXAMPLES = {
    "Background": [
        "In a related study of Ni(X-py)4(ClO4)2 complexes and with a range of substituent X on pyridine, Bull and Moore concluded that the effects of substitution at the 3- and 4-positions were too small to influence the magnitude of the ligand field splitting constant, Δ[41]."
    ],
    "Motivation": [
        "However, standard coupling chemistries using activating agents do not work well with benzotriazole dyes and we have investigated alternative strategies."
    ],
    "Method": [
        "A method was developed for the propargylamine modification of negatively charged dye labels and involves the addition of 6 modified nucleobases at the 5′-terminus close to the dye label."
    ],
    "Result": [
        "The results from these experiments (Table 2) show that the phototransformation of NO2 -> HONO is also effective when the electron donor is not a phenolic compound."
    ],
    "Conclusion": [
        "This initial study clearly demonstrates the high potential that SERRS Beacons have as a new class of molecular reporter."
    ],
}

CHATGPT_DEFINITION = {
    "Background": "A sentence that provides context, foundational knowledge, or relevant information about the research topic, existing theories, prior studies, or the broader scientific field in which the research is situated. It helps readers understand the background against which the research is conducted.",
    "Motivation": "A sentence that explains the reasons, objectives, or goals behind the research. It often includes statements about the research gap, the problem being addressed, the significance of the study, and why the research is important.",
    "Method": "A sentence that describes the research methods, techniques, procedures, and data collection processes used in the study. This category also encompasses details about the experimental design, data analysis, and any materials or instruments utilized.",
    "Result": "A sentence that presents the empirical findings, outcomes, observations, or data generated by the research. It includes quantitative and qualitative results, statistical analyses, tables, figures, and any other information related to the research findings.",
    "Conclusion": "A sentence that summarizes the key takeaways, implications, interpretations, or insights derived from the study's results. It often discusses the broader significance of the findings, suggests future research directions, and may reiterate the study's contributions to the field.",
}

CHATGPT_EXAMPLES = {
    "Background": [
        "Previous studies have shown a strong correlation between diet and cardiovascular health, with a focus on the impact of saturated fats and cholesterol levels."
    ],
    "Motivation": [
        "This research aims to address the current gap in our understanding of how genetic factors influence the development of neurological disorders, providing valuable insights into potential treatment strategies."
    ],
    "Method": [
        "We conducted a double-blind, randomized controlled trial with a sample size of 500 participants to assess the efficacy of the new drug in reducing symptoms of hypertension."
    ],
    "Result": [
        "The experimental group exhibited a significant decrease in blood pressure levels (p < 0.05) after eight weeks of treatment, as compared to the control group."
    ],
    "Conclusion": [
        "In conclusion, our findings suggest that the novel compound holds promise as an effective therapy for hypertension, opening up new avenues for the development of antihypertensive medications."
    ],
}

GUIDELINES = {
    "coresc": {
        "prompt": DEFAULT_TASK_PROMPT,
        "labels": LABELS,
        "definition": CORESC_DEFINTION,
        "examples": CORESC_EXAMPLES,
    },
    "llm_definitions": {
        "prompt": DEFAULT_TASK_PROMPT,
        "labels": LABELS,
        "definition": CHATGPT_DEFINITION,
        "examples": CHATGPT_EXAMPLES,
    },
}
